// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using aluno_API.Data;

namespace aluno_API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200904191534_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7");

            modelBuilder.Entity("aluno_API.Models.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DataNascimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sobrenome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProfessorId");

                    b.ToTable("Alunos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataNascimento = "01/01/1985",
                            Nome = "Adriano",
                            ProfessorId = 1,
                            Sobrenome = "Silva"
                        },
                        new
                        {
                            Id = 2,
                            DataNascimento = "01/01/1985",
                            Nome = "Bruno",
                            ProfessorId = 3,
                            Sobrenome = "Santos"
                        },
                        new
                        {
                            Id = 3,
                            DataNascimento = "01/01/1985",
                            Nome = "Florinda",
                            ProfessorId = 2,
                            Sobrenome = "Gomes"
                        });
                });

            modelBuilder.Entity("aluno_API.Models.Professor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Professores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Jose"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Pedro"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Maria"
                        });
                });

            modelBuilder.Entity("aluno_API.Models.Aluno", b =>
                {
                    b.HasOne("aluno_API.Models.Professor", "Professor")
                        .WithMany("Alunos")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
